//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.HREmployeeAddresses = new HashSet<HREmployeeAddress>();
            this.HREmployeeAddresses1 = new HashSet<HREmployeeAddress>();
        }
    
        public long Id { get; set; }
        public int IdCountry { get; set; }
        public int IdCityCategory { get; set; }
        public long IdCountryDistrict { get; set; }
        public string CityName { get; set; }
        public string CityNameNP { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CityCategory CityCategory { get; set; }
        public virtual Country Country { get; set; }
        public virtual CountryDistrict CountryDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddresses1 { get; set; }
    }
}
