//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountryDistrict()
        {
            this.Cities = new HashSet<City>();
            this.HREmployeeAddresses = new HashSet<HREmployeeAddress>();
            this.HREmployeeAddresses1 = new HashSet<HREmployeeAddress>();
            this.HREmployeeNationalIdentities = new HashSet<HREmployeeNationalIdentity>();
        }
    
        public long Id { get; set; }
        public int IdCountry { get; set; }
        public int IdCountryState { get; set; }
        public string CountryDistrictName { get; set; }
        public string CountryDistrictNameNP { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
        public virtual Country Country { get; set; }
        public virtual CountryState CountryState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddresses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeNationalIdentity> HREmployeeNationalIdentities { get; set; }
    }
}
