//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRDevice()
        {
            this.HRCompanyDeviceMonitors = new HashSet<HRCompanyDeviceMonitor>();
        }
    
        public long Id { get; set; }
        public long IdHRCompany { get; set; }
        public int IdHRDeviceModel { get; set; }
        public string HRDeviceName { get; set; }
        public string HRDeviceNameNP { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> CommunicationPort { get; set; }
        public Nullable<int> SerialPort { get; set; }
        public string SerialNumber { get; set; }
        public bool IsActive { get; set; }
        public bool IsRegister { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyDeviceMonitor> HRCompanyDeviceMonitors { get; set; }
        public virtual HRCompany HRCompany { get; set; }
        public virtual HRDeviceModel HRDeviceModel { get; set; }
    }
}
