//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRDesignation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRDesignation()
        {
            this.HREmployeeJobHistories = new HashSet<HREmployeeJobHistory>();
        }
    
        public long Id { get; set; }
        public long IdHRCompany { get; set; }
        public long IdHREmployeeCategory { get; set; }
        public string HRDesignationTitle { get; set; }
        public string HRDesignationTitleNP { get; set; }
        public string HRDesignationShortName { get; set; }
        public int HRDesignationOrder { get; set; }
        public int HRDesignationRank { get; set; }
        public decimal BasicSalary { get; set; }
        public int SalaryIncrementNumber { get; set; }
        public decimal SalaryIncrementRate { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> OverTimeAllowance { get; set; }
        public Nullable<decimal> RatePerMinute { get; set; }
        public decimal TotalSalary { get; set; }
        public bool IsPermanent { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HREmployeeCategory HREmployeeCategory { get; set; }
        public virtual HRCompany HRCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeJobHistory> HREmployeeJobHistories { get; set; }
    }
}
