//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeBankList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HREmployeeBankList()
        {
            this.HREmployeeBankAccounts = new HashSet<HREmployeeBankAccount>();
        }
    
        public long Id { get; set; }
        public string BankName { get; set; }
        public string BankNameNP { get; set; }
        public string BankCategory { get; set; }
        public string BankLocation { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string SwiftCode { get; set; }
        public string IBAN { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeBankAccount> HREmployeeBankAccounts { get; set; }
    }
}
