//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeJobHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HREmployeeJobHistory()
        {
            this.HREmployeeAttendanceHistories = new HashSet<HREmployeeAttendanceHistory>();
            this.HREmployeeKaajHistories = new HashSet<HREmployeeKaajHistory>();
            this.HREmployeeLeaveHistories = new HashSet<HREmployeeLeaveHistory>();
        }
    
        public long Id { get; set; }
        public long IdHREmployeeServiceType { get; set; }
        public long IdHREmployee { get; set; }
        public long IdHRCompany { get; set; }
        public Nullable<long> IdHRCompanyDivision { get; set; }
        public long IdHRDesignation { get; set; }
        public int IdHREmployeeJobStatus { get; set; }
        public int JobStatusCounter { get; set; }
        public bool IsCurrentStatus { get; set; }
        public bool IsHead { get; set; }
        public Nullable<System.DateTime> ImplementationDate { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string DocumentName { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HRCompany HRCompany { get; set; }
        public virtual HRCompanyDivision HRCompanyDivision { get; set; }
        public virtual HRDesignation HRDesignation { get; set; }
        public virtual HREmployee HREmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAttendanceHistory> HREmployeeAttendanceHistories { get; set; }
        public virtual HREmployeeServiceType HREmployeeServiceType { get; set; }
        public virtual HREmployeeJobStatu HREmployeeJobStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistories { get; set; }
    }
}
