//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HREmployee()
        {
            this.HRCompanyNotifications = new HashSet<HRCompanyNotification>();
            this.HREmployeeKaajHistories = new HashSet<HREmployeeKaajHistory>();
            this.HREmployeeLeaveHistories = new HashSet<HREmployeeLeaveHistory>();
            this.HREmployeeAddresses = new HashSet<HREmployeeAddress>();
            this.HREmployeeSalaryHistories = new HashSet<HREmployeeSalaryHistory>();
            this.HREmployeeBiometricTemplates = new HashSet<HREmployeeBiometricTemplate>();
            this.HREmployeeEducations = new HashSet<HREmployeeEducation>();
            this.HREmployeeProperties = new HashSet<HREmployeeProperty>();
            this.HREmployeeContacts = new HashSet<HREmployeeContact>();
            this.HREmployeeKaajHistories1 = new HashSet<HREmployeeKaajHistory>();
            this.HREmployeeCompanyFacilities = new HashSet<HREmployeeCompanyFacility>();
            this.HREmployeeBankAccounts = new HashSet<HREmployeeBankAccount>();
            this.HREmployeeAttendanceHistories = new HashSet<HREmployeeAttendanceHistory>();
            this.HREmployeeLeaveHistories1 = new HashSet<HREmployeeLeaveHistory>();
            this.HREmployeeMessageServices = new HashSet<HREmployeeMessageService>();
            this.HREmployeeKaajHistories2 = new HashSet<HREmployeeKaajHistory>();
            this.HREmployeeLeaveHistories2 = new HashSet<HREmployeeLeaveHistory>();
            this.HREmployeeMessageServices1 = new HashSet<HREmployeeMessageService>();
            this.SystemComments = new HashSet<SystemComment>();
            this.HREmployeeNationalIdentities = new HashSet<HREmployeeNationalIdentity>();
            this.MembershipProviders = new HashSet<MembershipProvider>();
            this.HREmployeeJobHistories = new HashSet<HREmployeeJobHistory>();
            this.SystemPermissionByHREmployees = new HashSet<SystemPermissionByHREmployee>();
        }
    
        public long Id { get; set; }
        public long IdHRCompany { get; set; }
        public long IdParent_HREmployee { get; set; }
        public Nullable<long> IdMotherTongue { get; set; }
        public Nullable<int> IdRelation { get; set; }
        public Nullable<int> IdBloodGroup { get; set; }
        public long IdGender { get; set; }
        public long IdMarital { get; set; }
        public string HREmployeeName { get; set; }
        public string HREmployeeNameNP { get; set; }
        public string Color { get; set; }
        public Nullable<long> IdEnroll { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string BirthPlace { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public Nullable<System.DateTime> RetiredDate { get; set; }
        public string Document { get; set; }
        public string Document1 { get; set; }
        public string RightEye { get; set; }
        public string LeftEye { get; set; }
        public string RightThumb { get; set; }
        public string LeftThumb { get; set; }
        public string Signature { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> TotalFamilyNumber { get; set; }
        public Nullable<int> TotalChild { get; set; }
        public bool IsDisabled { get; set; }
        public string Status { get; set; }
        public bool IsOfficier { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HRCompany HRCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyNotification> HRCompanyNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistories { get; set; }
        public virtual HREmployeeBloodGroup HREmployeeBloodGroup { get; set; }
        public virtual HREmployeeSex HREmployeeSex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeSalaryHistory> HREmployeeSalaryHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeBiometricTemplate> HREmployeeBiometricTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeEducation> HREmployeeEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeProperty> HREmployeeProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeContact> HREmployeeContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeCompanyFacility> HREmployeeCompanyFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeBankAccount> HREmployeeBankAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAttendanceHistory> HREmployeeAttendanceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistories1 { get; set; }
        public virtual HREmployeeMarital HREmployeeMarital { get; set; }
        public virtual HRLanguage HRLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeMessageService> HREmployeeMessageServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistories2 { get; set; }
        public virtual HREmployeeRelationType HREmployeeRelationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeMessageService> HREmployeeMessageServices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemComment> SystemComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeNationalIdentity> HREmployeeNationalIdentities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipProvider> MembershipProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeJobHistory> HREmployeeJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemPermissionByHREmployee> SystemPermissionByHREmployees { get; set; }
    }
}
