//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public long Id { get; set; }
        public Nullable<System.Guid> IdLogin { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string SessionId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string ActionName { get; set; }
        public string DeviceName { get; set; }
        public string DeviceOS { get; set; }
        public string BrowserName { get; set; }
        public string BrowserVersion { get; set; }
        public string LocationName { get; set; }
        public string AccessURL { get; set; }
        public string IllegalAccessMessage { get; set; }
        public string EventMessage { get; set; }
        public string ErrorMessage { get; set; }
        public string TerminalIP { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
