//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountryDistrict()
        {
            this.City = new HashSet<City>();
            this.City1 = new HashSet<City>();
            this.HREmployeeAddress = new HashSet<HREmployeeAddress>();
            this.HREmployeeAddress1 = new HashSet<HREmployeeAddress>();
            this.HREmployeeAddress2 = new HashSet<HREmployeeAddress>();
            this.HREmployeeAddress3 = new HashSet<HREmployeeAddress>();
            this.HREmployeeNationalIdentity = new HashSet<HREmployeeNationalIdentity>();
        }
    
        public long Id { get; set; }
        public int IdCountry { get; set; }
        public int IdCountryState { get; set; }
        public string CountryDistrictName { get; set; }
        public string CountryDistrictNameNP { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> City1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual CountryState CountryState { get; set; }
        public virtual CountryState CountryState1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddress1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddress2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddress3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeNationalIdentity> HREmployeeNationalIdentity { get; set; }
    }
}
