//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayOfWeekNP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DayOfWeekNP()
        {
            this.HRCompanyHREmployeeShiftRoasters = new HashSet<HRCompanyHREmployeeShiftRoaster>();
        }
    
        public int Id { get; set; }
        public string DOW { get; set; }
        public string DOWNP { get; set; }
        public string DOWShortNP { get; set; }
        public string DOWShort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyHREmployeeShiftRoaster> HRCompanyHREmployeeShiftRoasters { get; set; }
    }
}
