//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCalendar
    {
        public long Id { get; set; }
        public string NepDate { get; set; }
        public int NepYear { get; set; }
        public int NepMonth { get; set; }
        public int NepDay { get; set; }
        public System.DateTime EngDate { get; set; }
        public int EngYear { get; set; }
        public int EngMonth { get; set; }
        public int EngDay { get; set; }
        public string EventName { get; set; }
        public string FestivalName { get; set; }
        public bool IsWeekendHoliday { get; set; }
        public bool IsPublicHoliday { get; set; }
        public bool IsHolidayForMale { get; set; }
        public bool IsHolidayForFemale { get; set; }
        public bool IsHolidayForDisabled { get; set; }
        public Nullable<int> IdReligion { get; set; }
    
        public virtual HREmployeeReligion HREmployeeReligion { get; set; }
    }
}
