//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCompanyLeaveType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRCompanyLeaveType()
        {
            this.HREmployeeLeaveBalance = new HashSet<HREmployeeLeaveBalance>();
            this.HREmployeeLeaveManagement = new HashSet<HREmployeeLeaveManagement>();
            this.HREmployeeLeaveHistory = new HashSet<HREmployeeLeaveHistory>();
        }
    
        public long Id { get; set; }
        public long IdHRCompany { get; set; }
        public int IdMasterLeaveTitle { get; set; }
        public bool IsIncludeWeekend { get; set; }
        public bool IsIncludePublicHoliday { get; set; }
        public bool EligibleTempStaff { get; set; }
        public bool IsSaving { get; set; }
        public int TotalLeaveDay { get; set; }
        public int SavingLimitDay { get; set; }
        public int AdditionalDays { get; set; }
        public bool IsContinueLeave { get; set; }
        public bool IsForMale { get; set; }
        public bool IsForFemale { get; set; }
        public bool EnableHalfDay { get; set; }
        public bool IsReoccuring { get; set; }
        public int OccuringTime { get; set; }
        public bool IsRecommended { get; set; }
        public bool IsApprovalByHRCompanyHead { get; set; }
        public bool IsDocumentUpload { get; set; }
        public int DocUploadDeadLineDays { get; set; }
        public int ApprovalDeadLineDays { get; set; }
        public bool IsDeductFromOther { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsSataLeave { get; set; }
    
        public virtual MasterLeaveTitle MasterLeaveTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveBalance> HREmployeeLeaveBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveManagement> HREmployeeLeaveManagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistory { get; set; }
        public virtual HRCompany HRCompany { get; set; }
    }
}
