//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCompanyHREmployeeShiftRoaster
    {
        public long Id { get; set; }
        public long IdHRCompanyHREmployeeShiftDate { get; set; }
        public int IdDayOfWeekNP { get; set; }
        public Nullable<long> IdHRCompanyShiftRoaster { get; set; }
        public bool IsWeekend { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual DayOfWeekNP DayOfWeekNP { get; set; }
        public virtual HRCompanyHREmployeeShiftDate HRCompanyHREmployeeShiftDate { get; set; }
        public virtual HRCompanyShiftRoaster HRCompanyShiftRoaster { get; set; }
    }
}
