//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCompanyHistory
    {
        public long Id { get; set; }
        public long IdHRCompany { get; set; }
        public string OldHRCompanyName { get; set; }
        public string NewHRCompanyName { get; set; }
        public Nullable<long> OldIdParent_HRCompany { get; set; }
        public Nullable<long> NewIdParent_HRCompany { get; set; }
        public Nullable<int> OldIdHRCompanyType { get; set; }
        public Nullable<int> NewIdHRCompanyType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual HRCompany HRCompany { get; set; }
    }
}
