//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCompanyAssignNotification
    {
        public long Id { get; set; }
        public long IdNotification { get; set; }
        public long IdCompany { get; set; }
    
        public virtual HRCompanyNotification HRCompanyNotification { get; set; }
        public virtual HRCompanyNotification HRCompanyNotification1 { get; set; }
        public virtual HRCompany HRCompany { get; set; }
    }
}
