//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCompanyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRCompanyType()
        {
            this.HRCompanyType1 = new HashSet<HRCompanyType>();
            this.HRCompanyType11 = new HashSet<HRCompanyType>();
            this.HRCompanies = new HashSet<HRCompany>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdParent_CompanyType { get; set; }
        public string CompanyType { get; set; }
        public string CompanyTypeShortName { get; set; }
        public int OrderBy { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyType> HRCompanyType1 { get; set; }
        public virtual HRCompanyType HRCompanyType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyType> HRCompanyType11 { get; set; }
        public virtual HRCompanyType HRCompanyType3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompany> HRCompanies { get; set; }
    }
}
