//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRCompany()
        {
            this.HRCompanyAssignNotifications = new HashSet<HRCompanyAssignNotification>();
            this.HRCompanyDivisionTypes = new HashSet<HRCompanyDivisionType>();
            this.HRCompanyNotifications = new HashSet<HRCompanyNotification>();
            this.HRCompanyHREmployeeShiftDates = new HashSet<HRCompanyHREmployeeShiftDate>();
            this.HRCompanyHistories = new HashSet<HRCompanyHistory>();
            this.HRCompanySystemSupports = new HashSet<HRCompanySystemSupport>();
            this.HRCompanyDivisions = new HashSet<HRCompanyDivision>();
            this.HRCompanyLeaveTypes = new HashSet<HRCompanyLeaveType>();
            this.HRDesignations = new HashSet<HRDesignation>();
            this.HRDevices = new HashSet<HRDevice>();
            this.HRDevices1 = new HashSet<HRDevice>();
            this.HREmployees = new HashSet<HREmployee>();
            this.HREmployeeKaajHistories = new HashSet<HREmployeeKaajHistory>();
            this.HREmployeeRoles = new HashSet<HREmployeeRole>();
            this.HREmployeeServiceTypes = new HashSet<HREmployeeServiceType>();
            this.HREmployeeCategories = new HashSet<HREmployeeCategory>();
            this.HREmployeeLoanTitles = new HashSet<HREmployeeLoanTitle>();
            this.HREmployeeLeaveHistories = new HashSet<HREmployeeLeaveHistory>();
            this.HRPublicHolidays = new HashSet<HRPublicHoliday>();
            this.SystemComments = new HashSet<SystemComment>();
            this.SystemDatabaseBackups = new HashSet<SystemDatabaseBackup>();
            this.HREmployeeAttendanceHistories = new HashSet<HREmployeeAttendanceHistory>();
            this.HRCompanyShiftRoasters = new HashSet<HRCompanyShiftRoaster>();
            this.HRCompanyManualAttendance = new HashSet<HRCompanyManualAttendance>();
            this.HREmployeeJobHistories = new HashSet<HREmployeeJobHistory>();
            this.HRCompanyEmployeeOfficeLogs = new HashSet<HRCompanyEmployeeOfficeLog>();
        }
    
        public long Id { get; set; }
        public int IdHRCompanyType { get; set; }
        public Nullable<long> IdParent_HRCompany { get; set; }
        public int IdCompanyCode { get; set; }
        public int IdState { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNameNP { get; set; }
        public string CompanyShortName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public bool IsCentralLevelHRCompany { get; set; }
        public string Logo { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HRCompanyCode HRCompanyCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyAssignNotification> HRCompanyAssignNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyDivisionType> HRCompanyDivisionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyNotification> HRCompanyNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyHREmployeeShiftDate> HRCompanyHREmployeeShiftDates { get; set; }
        public virtual HRCompanyType HRCompanyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyHistory> HRCompanyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanySystemSupport> HRCompanySystemSupports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyDivision> HRCompanyDivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyLeaveType> HRCompanyLeaveTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRDesignation> HRDesignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRDevice> HRDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRDevice> HRDevices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployee> HREmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeRole> HREmployeeRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeServiceType> HREmployeeServiceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeCategory> HREmployeeCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLoanTitle> HREmployeeLoanTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPublicHoliday> HRPublicHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemComment> SystemComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemDatabaseBackup> SystemDatabaseBackups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAttendanceHistory> HREmployeeAttendanceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyShiftRoaster> HRCompanyShiftRoasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyManualAttendance> HRCompanyManualAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeJobHistory> HREmployeeJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyEmployeeOfficeLog> HRCompanyEmployeeOfficeLogs { get; set; }
    }
}
