//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeEducation
    {
        public long Id { get; set; }
        public int IdHREmployeeEducationType { get; set; }
        public long IdHREmployee { get; set; }
        public string CollegeName { get; set; }
        public string CollegeAddress { get; set; }
        public string DegreeName { get; set; }
        public string Score { get; set; }
        public Nullable<System.DateTime> StartedDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Document { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
        public string Document3 { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HREmployee HREmployee { get; set; }
        public virtual HREmployeeEducationType HREmployeeEducationType { get; set; }
        public virtual HREmployeeEducationType HREmployeeEducationType1 { get; set; }
    }
}
