//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeKaajHistory
    {
        public long Id { get; set; }
        public long IdHrCompany { get; set; }
        public long IdJob { get; set; }
        public int IdKaajType { get; set; }
        public long IdHREmployee { get; set; }
        public int IdCountry { get; set; }
        public Nullable<long> IdRecommendedBy { get; set; }
        public Nullable<long> IdApprovedBy { get; set; }
        public int KaajYearNP { get; set; }
        public string FiscalYear { get; set; }
        public string KaajRegistrationNumber { get; set; }
        public string KaajTitle { get; set; }
        public string KaajShortName { get; set; }
        public string KaajLocation { get; set; }
        public Nullable<int> KaajTakenNumber { get; set; }
        public string KaajPurpose { get; set; }
        public string VehicleUsedInKaaj { get; set; }
        public bool KaajExpenses { get; set; }
        public System.DateTime KaajFromDate { get; set; }
        public string KaajFromNP { get; set; }
        public Nullable<System.DateTime> KaajToDate { get; set; }
        public string KaajToNP { get; set; }
        public Nullable<System.TimeSpan> CheckInTime { get; set; }
        public Nullable<System.TimeSpan> CheckOutTime { get; set; }
        public Nullable<int> IdKaajStatus { get; set; }
        public Nullable<System.DateTime> RecommendedOn { get; set; }
        public string RecommendationBy { get; set; }
        public string RemarkRecommended { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public string RemarkApprovedBy { get; set; }
        public string Document { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
        public bool IsActive { get; set; }
        public bool IsNational { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual HRCompany HRCompany { get; set; }
        public virtual HRCompanyLeaveStatusType HRCompanyLeaveStatusType { get; set; }
        public virtual HREmployee HREmployee { get; set; }
        public virtual HREmployee HREmployee1 { get; set; }
        public virtual HREmployee HREmployee2 { get; set; }
        public virtual KaajType KaajType { get; set; }
        public virtual HREmployeeJobHistory HREmployeeJobHistory { get; set; }
    }
}
