//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeMedicalRecord
    {
        public System.Guid Id { get; set; }
        public long IdHREmployee { get; set; }
        public string MedicalTitle { get; set; }
        public string Remark { get; set; }
        public System.DateTime MedicalDate { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual HREmployee HREmployee { get; set; }
    }
}
