//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeLeaveManagement
    {
        public int Id { get; set; }
        public long IdHREmployee { get; set; }
        public long IdLeaveType { get; set; }
        public int IdMasterLeaveTitle { get; set; }
        public int LeaveYearNP { get; set; }
        public decimal TotalLeave { get; set; }
        public string Remarks { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HRCompanyLeaveType HRCompanyLeaveType { get; set; }
        public virtual HREmployee HREmployee { get; set; }
        public virtual MasterLeaveTitle MasterLeaveTitle { get; set; }
    }
}
