//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HREmployeeLoan()
        {
            this.HREmployeeLoanRepaymentSchedule = new HashSet<HREmployeeLoanRepaymentSchedule>();
        }
    
        public System.Guid Id { get; set; }
        public long IdHREmployee { get; set; }
        public int IdHREmployeeLoanTitle { get; set; }
        public int IdInstallmentMode { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal InterestRate { get; set; }
        public decimal PenaltyRateOnInterestDue { get; set; }
        public decimal PenaltyRateOnPrincipalDue { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HREmployee HREmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLoanRepaymentSchedule> HREmployeeLoanRepaymentSchedule { get; set; }
        public virtual HREmployeeLoanTitle HREmployeeLoanTitle { get; set; }
        public virtual LoanInstallmentMode LoanInstallmentMode { get; set; }
    }
}
