//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HREmployee()
        {
            this.HRCompanyHREmployeeShiftDate = new HashSet<HRCompanyHREmployeeShiftDate>();
            this.HRCompanyNotification = new HashSet<HRCompanyNotification>();
            this.HREmployeeLeaveHistory = new HashSet<HREmployeeLeaveHistory>();
            this.HREmployeeLeaveManagement = new HashSet<HREmployeeLeaveManagement>();
            this.HREmployeeMedicalRecord = new HashSet<HREmployeeMedicalRecord>();
            this.HREmployeeAddress = new HashSet<HREmployeeAddress>();
            this.HREmployeeSalaryHistory = new HashSet<HREmployeeSalaryHistory>();
            this.HREmployeeBiometricTemplate = new HashSet<HREmployeeBiometricTemplate>();
            this.HREmployeeEducation = new HashSet<HREmployeeEducation>();
            this.HREmployeeProperty = new HashSet<HREmployeeProperty>();
            this.HREmployeeContact = new HashSet<HREmployeeContact>();
            this.HREmployeeLeaveBalance = new HashSet<HREmployeeLeaveBalance>();
            this.HREmployeeNationalIdentity = new HashSet<HREmployeeNationalIdentity>();
            this.HREmployeeCompanyFacility = new HashSet<HREmployeeCompanyFacility>();
            this.HREmployeeBankAccount = new HashSet<HREmployeeBankAccount>();
            this.HREmployeeLoan = new HashSet<HREmployeeLoan>();
            this.HREmployeeLoanRepaymentSchedule = new HashSet<HREmployeeLoanRepaymentSchedule>();
            this.HREmployeeLeaveHistory1 = new HashSet<HREmployeeLeaveHistory>();
            this.HREmployeeAdvanceAmount = new HashSet<HREmployeeAdvanceAmount>();
            this.HREmployeeEveryTwelveDaysLeaveBalance = new HashSet<HREmployeeEveryTwelveDaysLeaveBalance>();
            this.HREmployeeMessageService = new HashSet<HREmployeeMessageService>();
            this.HREmployeeLeaveHistory2 = new HashSet<HREmployeeLeaveHistory>();
            this.HREmployeeMessageService1 = new HashSet<HREmployeeMessageService>();
            this.SystemComment = new HashSet<SystemComment>();
            this.SystemCommentResponse = new HashSet<SystemCommentResponse>();
            this.SystemCommentResponse1 = new HashSet<SystemCommentResponse>();
            this.SystemPermissionByHREmployee = new HashSet<SystemPermissionByHREmployee>();
            this.HREmployeeKaajHistories = new HashSet<HREmployeeKaajHistory>();
            this.HREmployeeKaajHistories1 = new HashSet<HREmployeeKaajHistory>();
            this.HREmployeeKaajHistories2 = new HashSet<HREmployeeKaajHistory>();
            this.MembershipProviders = new HashSet<MembershipProvider>();
            this.HREmployeeAttendanceHistories = new HashSet<HREmployeeAttendanceHistory>();
            this.HREmployeeAttendanceHistories1 = new HashSet<HREmployeeAttendanceHistory>();
            this.HRCompanyManualAttendance = new HashSet<HRCompanyManualAttendance>();
            this.HRCompanyManualAttendance1 = new HashSet<HRCompanyManualAttendance>();
            this.HREmployeeJobHistories = new HashSet<HREmployeeJobHistory>();
            this.HRCompanyEmployeeOfficeLogs = new HashSet<HRCompanyEmployeeOfficeLog>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdHRCompany { get; set; }
        public long IdParent_HREmployee { get; set; }
        public Nullable<long> IdMotherTongue { get; set; }
        public Nullable<int> IdRelation { get; set; }
        public Nullable<int> IdBloodGroup { get; set; }
        public Nullable<long> IdGender { get; set; }
        public Nullable<long> IdMarital { get; set; }
        public string HREmployeeName { get; set; }
        public string HREmployeeNameNP { get; set; }
        public string Color { get; set; }
        public Nullable<long> IdEnroll { get; set; }
        public string PISNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string BirthPlace { get; set; }
        public string DOBNP { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string AppointmentDateNP { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string RetiredDateNP { get; set; }
        public Nullable<System.DateTime> RetiredDate { get; set; }
        public string Document { get; set; }
        public string Document1 { get; set; }
        public string RightEye { get; set; }
        public string LeftEye { get; set; }
        public string RightThumb { get; set; }
        public string LeftThumb { get; set; }
        public string Signature { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> TotalFamilyNumber { get; set; }
        public Nullable<int> TotalChild { get; set; }
        public bool IsDisabled { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsOfficier { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> IdHREmployeeReligion { get; set; }
        public string PanNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyHREmployeeShiftDate> HRCompanyHREmployeeShiftDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyNotification> HRCompanyNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistory { get; set; }
        public virtual HREmployeeBloodGroup HREmployeeBloodGroup { get; set; }
        public virtual HREmployeeSex HREmployeeSex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveManagement> HREmployeeLeaveManagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeMedicalRecord> HREmployeeMedicalRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAddress> HREmployeeAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeSalaryHistory> HREmployeeSalaryHistory { get; set; }
        public virtual HREmployeeReligion HREmployeeReligion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeBiometricTemplate> HREmployeeBiometricTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeEducation> HREmployeeEducation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeProperty> HREmployeeProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeContact> HREmployeeContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveBalance> HREmployeeLeaveBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeNationalIdentity> HREmployeeNationalIdentity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeCompanyFacility> HREmployeeCompanyFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeBankAccount> HREmployeeBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLoan> HREmployeeLoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLoanRepaymentSchedule> HREmployeeLoanRepaymentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAdvanceAmount> HREmployeeAdvanceAmount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeEveryTwelveDaysLeaveBalance> HREmployeeEveryTwelveDaysLeaveBalance { get; set; }
        public virtual HREmployeeMarital HREmployeeMarital { get; set; }
        public virtual HRLanguage HRLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeMessageService> HREmployeeMessageService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeLeaveHistory> HREmployeeLeaveHistory2 { get; set; }
        public virtual HREmployeeRelationType HREmployeeRelationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeMessageService> HREmployeeMessageService1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemComment> SystemComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemCommentResponse> SystemCommentResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemCommentResponse> SystemCommentResponse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemPermissionByHREmployee> SystemPermissionByHREmployee { get; set; }
        public virtual HRCompany HRCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeKaajHistory> HREmployeeKaajHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipProvider> MembershipProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAttendanceHistory> HREmployeeAttendanceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeAttendanceHistory> HREmployeeAttendanceHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyManualAttendance> HRCompanyManualAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyManualAttendance> HRCompanyManualAttendance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HREmployeeJobHistory> HREmployeeJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyEmployeeOfficeLog> HRCompanyEmployeeOfficeLogs { get; set; }
    }
}
