//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeNationalIdentity
    {
        public long Id { get; set; }
        public long IdHREmployee { get; set; }
        public int IdNationalIdentityType { get; set; }
        public string IdentityNumber { get; set; }
        public long IssueDistrict { get; set; }
        public string IssueDateNP { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string ExpiryDateNP { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Document { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual CountryDistrict CountryDistrict { get; set; }
        public virtual HREmployee HREmployee { get; set; }
        public virtual HREmployeeNationalIdentityType HREmployeeNationalIdentityType { get; set; }
    }
}
