//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeLeaveHistory
    {
        public long Id { get; set; }
        public string LeaveRegistrationNumber { get; set; }
        public long IdHRCompany { get; set; }
        public long IdJob { get; set; }
        public Nullable<long> IdRecommandationBy { get; set; }
        public Nullable<long> IdApprovedBy { get; set; }
        public long IdHREmployee { get; set; }
        public long IdLeaveType { get; set; }
        public int IdMasterLeaveTitle { get; set; }
        public Nullable<int> LeaveYearNP { get; set; }
        public int LeaveYear { get; set; }
        public System.DateTime LeaveValidFrom { get; set; }
        public string LeaveValidFromNP { get; set; }
        public Nullable<System.DateTime> LeaveCancelFrom { get; set; }
        public string LeaveCancelFromNP { get; set; }
        public System.DateTime LeaveValidTo { get; set; }
        public string LeaveValidToNP { get; set; }
        public bool IsHalfDayCount { get; set; }
        public string LeaveReason { get; set; }
        public int IdLeaveStatus { get; set; }
        public Nullable<int> IdLeaveCancelStatus { get; set; }
        public string RecommandationRemark { get; set; }
        public Nullable<System.DateTime> RecommandationDate { get; set; }
        public string ApprovalRemark { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public bool IsActive { get; set; }
        public string Document { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
        public string TerminalIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HRCompanyLeaveStatusType HRCompanyLeaveStatusType { get; set; }
        public virtual HRCompanyLeaveStatusType HRCompanyLeaveStatusType1 { get; set; }
        public virtual HRCompanyLeaveType HRCompanyLeaveType { get; set; }
        public virtual HREmployee HREmployee { get; set; }
        public virtual HREmployee HREmployee1 { get; set; }
        public virtual HREmployee HREmployee2 { get; set; }
        public virtual MasterLeaveTitle MasterLeaveTitle { get; set; }
        public virtual HRCompany HRCompany { get; set; }
        public virtual HREmployeeJobHistory HREmployeeJobHistory { get; set; }
    }
}
