//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPublicHoliday
    {
        public long Id { get; set; }
        public long IdHRCompany { get; set; }
        public string HRPublicHolidayTitle { get; set; }
        public string HRPublicHolidayShortName { get; set; }
        public System.DateTime Fromdate { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool IsHolidayForMale { get; set; }
        public bool IsHolidayForFemale { get; set; }
        public bool IsNoHoliday { get; set; }
        public bool IsHolidayForDisabled { get; set; }
        public Nullable<int> IdReligion { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string TerminalIP { get; set; }
    
        public virtual HREmployeeReligion HREmployeeReligion { get; set; }
        public virtual HRCompany HRCompany { get; set; }
    }
}
