//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthNp
    {
        public int Id { get; set; }
        public string BS { get; set; }
        public string AD { get; set; }
        public string NepaliMonth { get; set; }
    }
}
