//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberSystemConversion
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public string NumberInNepali { get; set; }
        public string NumberInWord { get; set; }
        public string NumberInRoman { get; set; }
    }
}
